#!/usr/bin/env bash
# Ignore Errors and execute all commands
set +e
echo "Deploy Docker..."
sudo docker-compose up -d --force-recreate --build --remove-orphans && \
sudo docker-compose up -d --force-recreate
