version: '3'
services:
  nginx:
    image: nginx:1.13.12
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    # Note: `unless-stopped` option doesn't restart consistently on boot
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen:0.7.3
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    # stable version is between v1.8.1 and v1.9, created 2018-04-25T13:59:13.505051021Z, to avoid BIO_new_file error
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
#      ACME_CA_URI: "https://acme-staging.api.letsencrypt.org/directory"
#      DEBUG: "true"

  # Add new websites steps:
  #   1. Update `WEBSITES_DOMAINS` in `.env` file
  #   2. Clone website repo to `WEBSITES_PATH`
  #   3. $ docker-compose up -d
  websites:
    image: nginx:1.13.12
    container_name: websites
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    volumes:
      - ./websites/conf.d:/etc/nginx/conf.d
      - ${WEBSITES_PATH}:/var/www:ro
    environment:
      VIRTUAL_HOST: ${WEBSITES_DOMAINS}
      LETSENCRYPT_HOST: ${WEBSITES_DOMAINS}
      LETSENCRYPT_EMAIL: ${WEBSITES_EMAIL}

networks:
  default:
    external:
      name: webproxy
